### PR TITLE
Cross val weightsv2

### PR DESCRIPTION
**Pull request by ApproximateIdentity**
This branch changes Cyclops so that cross-validation can be used with weights. I have spent a lot of time working on this code and am finally feeling reasonably familiar with the codebase, but I would highly appreciate another pair of critical eyes on the changes I've made. Thanks a lot.

### CODE REVIEW

**Comment by msuchard** [comment]
I am happy to do a code-review before merging.  Here is a list of TODO items before merger:

1. Add `testthat` unit-tests to demonstrate functionality and ensure that future changes do not break your code.
2. Restore deleted imputation code and (possibility) move into a deprecated folder.

**Comment by ApproximateIdentity** [comment]
Excellent thanks a lot.What is your preference as to what to do with the imputation code? Obviously I'd prefer to delete it, but if it were to be moved to a deprecated folder, would a folder in the base of the repo be okay? I.e. outside of the src/ folder like say root/deprecated/imputation/ ?

The tests will take a bit longer, but I'll get on that right away.

**Comment by msuchard** [comment]
Unit-tests should be straight-forward and really should be written before one starts to modify the code (test-driven-development).   Use, for example, `simulateCyclopsData()`.  Then create a Cyclops object using all the data and some 0/1 weights.  Also create a Cyclops object where you have masked off the 0 weight entries beforehand the create step.

**Comment by ApproximateIdentity** [comment]
Sorry about falling off the radar. I had this weird light sickness that developed into something much worse last week and essentially took me out of commission for a week. It feels good to get back to this.

Yeah I agree with the general test-first philosophy, but my problem in this case was that I had very little understanding about the internal api so it was easier just to let it evolve and throw away my code if it didn't make sense.

Thanks about the tip of masking. I didn't think about doing it that way, but it should have been obvious that I should have gone about it like that. I'll get on that right away. Thanks for the tip!

**Comment by ApproximateIdentity** [comment]
I've gotten some odd results that I'm having trouble understanding and now have the following question: What does it mean exactly for a row's weight to be set to 0? Does it mean that that row is entirely invisible during the computation? Or does it mean that the row remains, but its value is set to 0? I.e. is it a "mask" that removes data from the model or does it scale the row's value (in this case to 0)?

Hopefully the question makes sense. I tried to answer it myself, by tracing through the execution of the program, but was having trouble understanding exactly where the weigths' values enter into the computation.

**Comment by msuchard** [comment]
Weights should scale the contribution of each row to the data likelihood and its gradient.

**Comment by ApproximateIdentity** [comment]
Hi Marc thanks for the response. I just wanted to make sure I'm 100% clear on this exactly. Say I'm in the following situation. Both X and y are given by the following single column matrix.

```
1
0
1
0
```

Let's say the weights I choose are the following:

```
1
1
0
0
```

If I fit with these weights would it be equivalent to changing the y vector to the following?

```
1
0
0
0
```

The reason I'm wondering is because it seems like I _cannot_ use weights to mimic a train/test split if it's like this. Fitting with weights will not get the same thing as fitting by dropping the rows entirely. This is of course orthogonal to the code in question (and hence this pull request), but it is the reason I wrote this code in the first place so I should know if I can't use this the way I wanted.

Am I misunderstanding things?

**Comment by msuchard** [comment]
The following (logistic) regressions should be exactly (same bit-stream when fit) equivalent:

```
y | x | weight
--------------
1 | 1 | 1
0 | 2 | 1
1 | 3 | 0
0 | 4 | 0
```

and

```
y | x 
-----
1 | 1
0 | 2
```

There exist, I believe, a couple of `testthat` unit-tests to check this.

**Comment by msuchard** [comment]
How are the test-units coming?

**Pull request closed without merging**
